version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: 'bitnami/postgresql:latest'
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: fate
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
